spring.application.name=accounts-service
server.port=8081

spring.profiles.default=h2
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.show-actuator=true
springdoc.override-with-generic-response=false
validation.base-url=${VALIDATION_BASE_URL:http://localhost:8082}
validation.timeout-ms=${VALIDATION_TIMEOUT_MS:800}